path: []
inputs:
  aclNames:
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: permit
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: anyany
      type: ip
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: deny
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: any deny
      type: ip
  devices:
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: BLUE End Device
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '2'
              tags:
                query: device:95A0ADFCE36FFA14EDE87009E17D4CA2
            - inputs:
                stackMember: '1'
              tags:
                query: device:33D3493C8463E4152C9ED22CF95DB8B2
          vlanInterfaces:
            - createVlanOnly: false
              description: S1F1-GREEN
              ipPrefix: 2.0.0.1/24
              vlanId: 1/200
              vrf: GREEN
            - createVlanOnly: false
              description: S1F1-BLACK
              ipPrefix: 4.3.1.11/24
              vlanId: 1/431
              vrf: BLACK
            - createVlanOnly: false
              description: S1F2-RED
              ipPrefix: 3.1.9.13/24
              vlanId: 2/319
              vrf: RED
            - createVlanOnly: false
              description: S1F2-GREEN
              ipPrefix: 2.0.1.1/24
              vlanId: 2/201
              vrf: GREEN
            - createVlanOnly: false
              description: S1F2-GREEN
              ipPrefix: 2.1.1.1/24
              vlanId: 2/211
              vrf: GREEN
            - createVlanOnly: false
              description: S1F1-GREEN
              ipPrefix: 2.1.0.1/24
              vlanId: 1/210
              vrf: GREEN
      tags:
        query: Edge-Router-Domain:Site1
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: ''
              enabled: true
              interfaceName: e2/2,2/6
              interfaceProfileName: TRUNK
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:6F1A0135F44B1AA9D25473177E89A98A
            - inputs:
                stackMember: '3'
              tags:
                query: device:8E39D56C43FB0A6B73B455AFF4782391
            - inputs:
                stackMember: '2'
              tags:
                query: device:DC5DA2A1D61E5DAD8CFE52A4125A477A
          vlanInterfaces:
            - createVlanOnly: false
              description: S2F1-RED
              ipPrefix: 3.1.9.9/24
              vlanId: 1/319
              vrf: RED
            - createVlanOnly: false
              description: S2F1-GREEN
              ipPrefix: 2.0.2.1/24
              vlanId: 1/202
              vrf: GREEN
            - createVlanOnly: false
              description: S2F1-GREEN
              ipPrefix: 2.1.2.1/24
              vlanId: 1/212
              vrf: GREEN
            - createVlanOnly: false
              description: S2F1-BLACK
              ipPrefix: 4.3.1.9/24
              vlanId: 1/431
              vrf: BLACK
      tags:
        query: Edge-Router-Domain:Site2
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: ''
              enabled: true
              interfaceName: e6
              interfaceProfileName: TRUNK
              stackNumber: '6'
          stack:
            - inputs:
                stackMember: '6'
              tags:
                query: device:9C809332310607508C60E4740F3C9359
      tags:
        query: Edge-Router-Domain:FW-Border-Router
  dot1XProfiles:
    - dot1XProfileName: d
      dot1x: {}
      portSecurity: {}
  loggingProfiles:
    - logging:
        congestionDrops: none
        linkStatus: enabled
        spanningTree: none
        stormControl: none
      loggingProfileName: L1
  poeProfiles:
    - description: ''
      poe:
        legacyDetect: disabled
        linkDownAction: maintain
        poeNegotiationLldp: disabled
        poeRebootAction: maintain
        poeShutdownAction: maintain
        poeWattsLimit: '3'
        poeWattsLimitClass: '0'
        priority: medium
      poeProfileName: poe1
  qosInstances:
    - classMaps:
        - classMapName: CM0
          match: ''
          matchValue: ''
          type: qos
      classification: []
      devices: []
      instanceName: Q1
      policyMaps:
        - classDefault: '3'
          classMap:
            - classMap: CM0
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '5'
          policyMapName: PM1
          type: qos
      rewriteRules: []
      serviceProfiles:
        - cos: ''
          dscp: ''
          policyMap: PM1
          profileName: Q1
          trust: none
          txQueue: []
      trafficClassToQueue: []
    - classMaps:
        - classMapName: CM3
          match: ip
          matchValue: ''
          type: qos
      classification:
        - classifierValues: 34 36 48
          trafficClass: '0'
          type: dscp
      devices: []
      instanceName: Q2
      policyMaps:
        - classDefault: ''
          classMap:
            - classMap: CM3
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '7'
          policyMapName: PM3
          type: qos
      rewriteRules: []
      serviceProfiles: []
      trafficClassToQueue:
        - dscp: ''
          queue: '1'
          trafficClass: '0'
        - dscp: ''
          queue: '0'
          trafficClass: '1'
  vlanProfiles:
    - allowedVlans: ''
      ipaddress: ''
      lacpEnabled: true
      mlagEnabled: false
      mode: trunk
      name: Trunk
      nativeVlanId: 1
      phoneTrunk: tagged
      phoneVlanId: 0
      portFastEnabled: false
      profileDescription: ''
      speed: auto
