path: []
inputs:
  devices:
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: p1
                speed: auto
            tags:
              query: interface:Management1@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet7@eos1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@eos1
      tags:
        query: device:eos1
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet5@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet3@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos2
      tags:
        query: device:eos13
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@eos4
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet1@eos4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos4
      tags:
        query: device:eos4
    - inputs:
        interface: []
      tags:
        query: device:eos16
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet5@eos2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos2
      tags:
        query: device:eos17
    - inputs:
        interface: []
      tags:
        query: device:eos9
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos8
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos8
      tags:
        query: device:eos8
    - inputs:
        interface: []
      tags:
        query: device:eos18
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: false
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet4@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet6@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet7@eos6
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@eos6
      tags:
        query: device:eos6
    - inputs:
        interface: []
      tags:
        query: device:eos2
    - inputs:
        interface: []
      tags:
        query: device:eos12
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@eos3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos3
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet6@eos3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos3
      tags:
        query: device:eos3
    - inputs:
        interface: []
      tags:
        query: device:eos20
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet6@eos3
      tags:
        query: device:eos7
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos4
      tags:
        query: device:eos10
    - inputs:
        interface: []
      tags:
        query: device:eos19
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos6
      tags:
        query: device:eos14
    - inputs:
        interface: []
      tags:
        query: device:eos15
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet2@eos11
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@eos11
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@eos11
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@eos11
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@eos11
      tags:
        query: device:eos11
    - inputs:
        interface: []
      tags:
        query: device:eos5
  profiles:
    - accessVlanId: 0
      allowedVlans: 1-4000
      mlagEnabled: false
      mode: trunk
      name: trunk
      nativeVlanId: 1
      phoneVlanId: 0
      profileDescription: trunk
      speed: auto
