path: []
inputs:
  sites:
    - aclNames: []
      devices:
        - inputs:
            devicesGroup:
              interfaceRanges: []
              stack:
                - inputs:
                    stackMember: '2'
                  tags:
                    query: device:eos13
                - inputs:
                    stackMember: '3'
                  tags:
                    query: device:eos12
                - inputs:
                    stackMember: '1'
                  tags:
                    query: device:eos11
              vlanInterfaces:
                - createVlanOnly: false
                  defaultGatewayNextHop: ''
                  description: ''
                  ipAddressVirtual: ''
                  ipPrefix: 8.3.6.1/31
                  secIp: []
                  virtualRouterAddress: 15.15.15.1/24
                  vlanId: 1/15,2/15
                  vrf: ''
                - createVlanOnly: false
                  defaultGatewayNextHop: 15.15.15.1
                  description: ''
                  ipAddressVirtual: ''
                  ipPrefix: 15.15.15.4/24
                  secIp: []
                  stackNumber: '3'
                  virtualRouterAddress: ''
                  vlanId: '15'
                  vrf: ''
          tags:
            query: vStack:Campus-eos11-eos12-eos13
      dot1XProfiles: []
      interfaceProfiles:
        - interfaceProfilesName: TRUNK
          vlanProfile: TRUNK
      loggingProfiles: []
      pimProfiles: []
      poeProfiles: []
      ptpProfiles: []
      qosInstances: []
      siteName: Campus-eos11-eos12-eos13
      stormControlProfiles: []
      switches: []
      vlanProfiles:
        - allowedVlans: ''
          bpduGuardEnabled: false
          commandLine: ''
          dhcpHelpers: []
          ipaddress: ''
          lacpEnabled: false
          mlagEnabled: false
          mode: trunk
          name: TRUNK
          nativeVlanId: 1
          phoneVlanId: 0
          portFastEnabled: false
          profileDescription: TRUNK
          profileIpAddressVirtual: ''
          vlanName: ''
    - aclNames: []
      devices:
        - inputs:
            devicesGroup:
              interfaceRanges: []
              stack:
                - inputs:
                    stackMember: '1'
                  tags:
                    query: device:eos6
                - inputs:
                    stackMember: '2'
                  tags:
                    query: device:eos8
                - inputs:
                    stackMember: '5'
                  tags:
                    query: device:eos14
                - inputs:
                    stackMember: '3'
                  tags:
                    query: device:eos15
                - inputs:
                    stackMember: '4'
                  tags:
                    query: device:eos18
              vlanInterfaces:
                - createVlanOnly: false
                  defaultGatewayNextHop: ''
                  description: '15'
                  ipAddressVirtual: ''
                  ipPrefix: 7.5.4.0/31
                  secIp: []
                  virtualRouterAddress: 13.13.13.1/24
                  vlanId: 1/13,2/13
                  vrf: ''
                - createVlanOnly: false
                  defaultGatewayNextHop: 13.13.13.1
                  description: '13'
                  ipAddressVirtual: ''
                  ipPrefix: 13.13.13.4/24
                  secIp: []
                  stackNumber: '3'
                  virtualRouterAddress: ''
                  vlanId: '13'
                  vrf: ''
                - createVlanOnly: false
                  defaultGatewayNextHop: 13.13.13.1
                  description: '13'
                  ipAddressVirtual: ''
                  ipPrefix: 13.13.13.5/24
                  secIp: []
                  stackNumber: '4'
                  virtualRouterAddress: ''
                  vlanId: '13'
                  vrf: ''
                - createVlanOnly: false
                  defaultGatewayNextHop: 13.13.13.1
                  description: '13'
                  ipAddressVirtual: ''
                  ipPrefix: 13.13.13.6/24
                  secIp: []
                  stackNumber: '5'
                  virtualRouterAddress: ''
                  vlanId: '13'
                  vrf: ''
          tags:
            query: vStack:Campus-eos6-eos8-eos14-eos15-eos18
      dot1XProfiles: []
      interfaceProfiles: []
      loggingProfiles: []
      pimProfiles: []
      poeProfiles: []
      ptpProfiles: []
      qosInstances: []
      siteName: Campus-eos6-eos8-eos14-eos15-eos18
      stormControlProfiles: []
      switches: []
      vlanProfiles: []
    - aclNames: []
      devices:
        - inputs:
            devicesGroup:
              interfaceRanges: []
              stack:
                - inputs:
                    stackMember: '1'
                  tags:
                    query: device:eos9
              vlanInterfaces:
                - createVlanOnly: false
                  defaultGatewayNextHop: ''
                  description: '14'
                  ipAddressVirtual: ''
                  ipPrefix: 14.14.14.2/24
                  secIp: []
                  stackNumber: '1'
                  virtualRouterAddress: ''
                  vlanId: '14'
                  vrf: DC-L3EVPN1
          tags:
            query: vStack:Server-eos9
      dot1XProfiles: []
      interfaceProfiles: []
      loggingProfiles: []
      pimProfiles: []
      poeProfiles: []
      ptpProfiles: []
      qosInstances: []
      siteName: Server-eos9
      stormControlProfiles: []
      switches: []
      vlanProfiles: []
