path: []
inputs:
  devices:
    - inputs:
        interface: []
      tags:
        query: device:A4A500F1BEFF8C1C20F38D909000E85D
    - inputs:
        interface: []
      tags:
        query: device:720AA07C91F23A7097711AB1BC2BC5C8
    - inputs:
        interface: []
      tags:
        query: device:6F1A0135F44B1AA9D25473177E89A98A
    - inputs:
        interface: []
      tags:
        query: device:2D815C770E309B6128991597CE4A7FBC
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                description: port
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet6@8E39D56C43FB0A6B73B455AFF4782391
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@8E39D56C43FB0A6B73B455AFF4782391
      tags:
        query: device:8E39D56C43FB0A6B73B455AFF4782391
    - inputs:
        interface: []
      tags:
        query: device:64EF12189F62BD136902F91CE45AD6C7
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                description: port
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet3@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@DC5DA2A1D61E5DAD8CFE52A4125A477A
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@DC5DA2A1D61E5DAD8CFE52A4125A477A
      tags:
        query: device:DC5DA2A1D61E5DAD8CFE52A4125A477A
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet4@eos8
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet5@eos8
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@eos8
      tags:
        query: device:44204EB637B15866E4BFC29E1AE077D5
    - inputs:
        interface: []
      tags:
        query: device:95A0ADFCE36FFA14EDE87009E17D4CA2
    - inputs:
        interface: []
      tags:
        query: device:70A489918C1899B93D79CECE42175232
    - inputs:
        interface: []
      tags:
        query: device:6AB72AE457D3B1805E6617A3FB8A6CDE
    - inputs:
        interface: []
      tags:
        query: device:04CDEE3CE0255DCD84BF35D8DB831D4A
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@1AA475846FCB995415949C85C651A277
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@1AA475846FCB995415949C85C651A277
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@1AA475846FCB995415949C85C651A277
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet5@1AA475846FCB995415949C85C651A277
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@1AA475846FCB995415949C85C651A277
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@1AA475846FCB995415949C85C651A277
      tags:
        query: device:1AA475846FCB995415949C85C651A277
    - inputs:
        interface: []
      tags:
        query: device:2B11928CFAFBC54EF61879C72DF27B22
    - inputs:
        interface: []
      tags:
        query: device:33D3493C8463E4152C9ED22CF95DB8B2
    - inputs:
        interface: []
      tags:
        query: device:9C4E0F12E9D8043EA2475ED2FAEF8954
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@9C809332310607508C60E4740F3C9359
          - inputs:
              intfConfig:
                accessVlan: 0
                description: port
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet4@9C809332310607508C60E4740F3C9359
      tags:
        query: device:9C809332310607508C60E4740F3C9359
    - inputs:
        interface: []
      tags:
        query: device:9CE609D7A3B7F69147CAC1618770ABD7
    - inputs:
        interface: []
      tags:
        query: device:AA24D1DFC5C00C00061456D452CE6317
    - inputs:
        interface: []
      tags:
        query: device:CA324945A9E495617368513B42B80A63
  profiles:
    - accessVlanId: 0
      allowedVlans: 1-4000
      mlagEnabled: false
      mode: trunk
      name: trunk
      nativeVlanId: 1
      phoneVlanId: 0
      profileDescription: trunk
      speed: auto
