path: []
inputs:
  devices:
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: p1
                speed: auto
            tags:
              query: interface:Management1@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet7@EOS1
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@EOS1
      tags:
        query: device:EOS1
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Management1@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet5@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet3@EOS2
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@EOS2
      tags:
        query: device:EOS2
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 15
                enabled: true
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet6@EOS3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@EOS3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@EOS3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet3@EOS3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS3
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@EOS3
      tags:
        query: device:EOS3
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@EOS4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet4@EOS4
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: false
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet3@EOS4
          - inputs:
              intfConfig:
                accessVlan: 15
                enabled: true
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet1@EOS4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS4
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet5@EOS4
      tags:
        query: device:EOS4
    - inputs:
        interface: []
      tags:
        query: device:EOS5
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet6@EOS6
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet4@EOS6
      tags:
        query: device:EOS6
    - inputs:
        interface: []
      tags:
        query: device:EOS7
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                profile: ''
                speed: auto
            tags:
              query: interface:Ethernet4@EOS8
          - inputs:
              intfConfig:
                accessVlan: 0
                enabled: true
                profile: trunk
                speed: auto
            tags:
              query: interface:Ethernet5@EOS8
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS8
      tags:
        query: device:EOS8
    - inputs:
        interface:
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet1@EOS9
          - inputs:
              intfConfig:
                accessVlan: 0
                speed: auto
            tags:
              query: interface:Ethernet2@EOS9
      tags:
        query: device:EOS9
    - inputs:
        interface: []
      tags:
        query: device:EOS10
    - inputs:
        interface: []
      tags:
        query: device:EOS11
    - inputs:
        interface: []
      tags:
        query: device:EOS12
    - inputs:
        interface: []
      tags:
        query: device:EOS13
    - inputs:
        interface: []
      tags:
        query: device:EOS14
    - inputs:
        interface: []
      tags:
        query: device:EOS17
    - inputs:
        interface: []
      tags:
        query: device:EOS18
    - inputs:
        interface: []
      tags:
        query: device:EOS19
    - inputs:
        interface: []
      tags:
        query: device:EOS16
    - inputs:
        interface: []
      tags:
        query: device:EOS15
    - inputs:
        interface: []
      tags:
        query: device:EOS20
  profiles:
    - accessVlanId: 0
      allowedVlans: 2-20
      mlagEnabled: false
      mode: trunk
      name: trunk
      nativeVlanId: 1
      phoneVlanId: 0
      profileDescription: trunk
      speed: auto
