path: []
inputs:
  aclNames:
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: permit
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: anyany
      type: ip
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: deny
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: any deny
      type: ip
  devices:
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: INT-FW-BR-eos3
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '3'
            - description: INT-FW-BR-eos1
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '3'
              tags:
                query: device:8E39D56C43FB0A6B73B455AFF4782391
            - inputs:
                stackMember: '1'
              tags:
                query: device:9CE609D7A3B7F69147CAC1618770ABD7
          vlanInterfaces:
            - advancedSettings: {}
              createVlanOnly: false
              description: blue
              ipPrefix: 1.2.3.1/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '123'
              vrf: blue
            - advancedSettings: {}
              createVlanOnly: false
              description: green
              ipPrefix: 2.3.5.1/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '235'
              vrf: green
            - advancedSettings: {}
              createVlanOnly: false
              description: red
              ipPrefix: ''
              stackNumber: '1'
              virtualRouterAddress: 3.1.9.1/24
              vlanId: '319'
              vrf: red
      tags:
        query: Edge-Router-Domain:Internal-FW-Border-Router
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: EXT-FW
              enabled: true
              interfaceName: e6
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:9C809332310607508C60E4740F3C9359
          vlanInterfaces:
            - description: red
              stackNumber: '1'
              virtualRouterAddress: 3.1.9.9/24
              vlanId: '319'
              vrf: red
      tags:
        query: Edge-Router-Domain:External-FW-Border-Router
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: TO-END-DEVICES
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
          stack:
            - inputs:
                stackMember: '2'
              tags:
                query: device:95A0ADFCE36FFA14EDE87009E17D4CA2
            - inputs:
                stackMember: '1'
              tags:
                query: device:33D3493C8463E4152C9ED22CF95DB8B2
          vlanInterfaces:
            - advancedSettings:
                dhcpHelpers:
                  - helperAddress: 5.0.1.14
                  - helperAddress: 5.0.0.14
                secIp:
                  - secPrefix: 2.3.4.111/24
                  - secPrefix: 2.3.4.112/24
                  - secPrefix: 2.3.4.113/24
              createVlanOnly: false
              description: blue-L3
              ipPrefix: 2.3.4.11/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '234'
              vrf: blue
            - advancedSettings: {}
              createVlanOnly: false
              description: BLACK-P2P
              ipPrefix: 4.3.1.11/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '431'
              vrf: BLACK
            - advancedSettings:
                ipAddressVirtual: 4.3.2.1/24
              createVlanOnly: false
              description: green-L3-L2
              ipPrefix: ''
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green
      tags:
        query: Edge-Router-Domain:Site1
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: EOS8
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '2'
            - description: EOS16
              enabled: true
              interfaceName: e6
              interfaceProfileName: TRUNK
              stackNumber: '2'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:6F1A0135F44B1AA9D25473177E89A98A
            - inputs:
                stackMember: '2'
              tags:
                query: device:DC5DA2A1D61E5DAD8CFE52A4125A477A
          vlanInterfaces:
            - advancedSettings:
                ipAddressVirtual: 4.3.2.1/24
              createVlanOnly: false
              description: green
              ipPrefix: ''
              stackNumber: ''
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green
            - advancedSettings: {}
              createVlanOnly: false
              description: BLACK-P2P
              ipPrefix: 4.3.1.4/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '431'
              vrf: BLACK
      tags:
        query: Edge-Router-Domain:Site2
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: floor1-1
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:9C4E0F12E9D8043EA2475ED2FAEF8954
          vlanInterfaces:
            - advancedSettings:
                defaultGatewayNextHop: 3.1.9.7
              createVlanOnly: false
              description: red-floor2-1
              ipPrefix: 3.1.9.212/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor2
            - advancedSettings:
                defaultGatewayNextHop: 3.1.9.7
              createVlanOnly: false
              description: red-floor1-1
              ipPrefix: 3.1.9.121/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor1
            - advancedSettings:
                defaultGatewayNextHop: 3.1.9.7
              createVlanOnly: false
              description: gray-floor1-1
              ipPrefix: 3.2.0.121/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: gray-floor1
            - advancedSettings:
                defaultGatewayNextHop: 2.3.4.11
              createVlanOnly: false
              description: blue-floor1-1
              ipPrefix: 2.3.4.121/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '234'
              vrf: blue-floor1
            - advancedSettings:
                defaultGatewayNextHop: 4.3.2.1
              createVlanOnly: false
              description: green-floor1-1
              ipPrefix: 4.3.2.121/24
              stackNumber: ''
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green-floor1
      tags:
        query: End-Devices:Site1
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: floor2-1
              enabled: true
              interfaceName: e1
              interfaceProfileName: TRUNK
              stackNumber: '1'
            - description: floor2-2
              enabled: true
              interfaceName: e1
              interfaceProfileName: TRUNK
              stackNumber: '2'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:1AA475846FCB995415949C85C651A277
            - inputs:
                stackMember: '2'
              tags:
                query: device:2B11928CFAFBC54EF61879C72DF27B22
          vlanInterfaces:
            - advancedSettings:
                defaultGatewayNextHop: 3.1.9.7
              createVlanOnly: false
              description: red-floor2-1
              ipPrefix: 3.1.9.8/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor2
            - advancedSettings:
                defaultGatewayNextHop: 3.1.9.7
              createVlanOnly: false
              description: red-floor2-2
              ipPrefix: 3.1.9.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor2
            - advancedSettings:
                defaultGatewayNextHop: 3.2.0.14
              createVlanOnly: false
              description: gray-floor2-1
              ipPrefix: 3.2.0.8/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '320'
              vrf: gray-floor2
            - advancedSettings:
                defaultGatewayNextHop: 3.2.0.14
              createVlanOnly: false
              description: gray-floor2-2
              ipPrefix: 3.2.0.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '320'
              vrf: gray-floor2
      tags:
        query: End-Devices:Site2
  dot1XProfiles:
    - dot1XProfileName: d
      dot1x: {}
      portSecurity: {}
  loggingProfiles:
    - logging:
        congestionDrops: none
        linkStatus: enabled
        spanningTree: none
        stormControl: none
      loggingProfileName: L1
  poeProfiles:
    - description: ''
      poe:
        legacyDetect: disabled
        linkDownAction: maintain
        poeNegotiationLldp: disabled
        poeRebootAction: maintain
        poeShutdownAction: maintain
        poeWattsLimit: '3'
        poeWattsLimitClass: '0'
        priority: medium
      poeProfileName: poe1
  qosInstances:
    - classMaps:
        - classMapName: CM0
          match: ''
          matchValue: ''
          type: qos
      classification: []
      devices: []
      instanceName: Q1
      policyMaps:
        - classDefault: '3'
          classMap:
            - classMap: CM0
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '5'
          policyMapName: PM1
          type: qos
      rewriteRules: []
      serviceProfiles:
        - cos: ''
          dscp: ''
          policyMap: PM1
          profileName: Q1
          trust: none
          txQueue: []
      trafficClassToQueue: []
    - classMaps:
        - classMapName: CM3
          match: ip
          matchValue: ''
          type: qos
      classification:
        - classifierValues: 34 36 48
          trafficClass: '0'
          type: dscp
      devices: []
      instanceName: Q2
      policyMaps:
        - classDefault: ''
          classMap:
            - classMap: CM3
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '7'
          policyMapName: PM3
          type: qos
      rewriteRules: []
      serviceProfiles: []
      trafficClassToQueue:
        - dscp: ''
          queue: '1'
          trafficClass: '0'
        - dscp: ''
          queue: '0'
          trafficClass: '1'
  vlanProfiles:
    - allowedVlans: ''
      ipaddress: ''
      lacpEnabled: true
      mlagEnabled: false
      mode: trunk
      name: Trunk
      nativeVlanId: 1
      phoneTrunk: tagged
      phoneVlanId: 0
      portFastEnabled: false
      profileDescription: ''
      speed: auto
