path: []
inputs:
  aclNames:
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: permit
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: anyany
      type: ip
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: deny
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: any deny
      type: ip
  devices:
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: INT-FW-BR
              enabled: true
              interfaceName: e1/2,3/2
              interfaceProfileName: TRUNK
              stackNumber: ''
          stack:
            - inputs:
                stackMember: '3'
              tags:
                query: device:eos3
            - inputs:
                stackMember: '1'
              tags:
                query: device:oes1
          vlanInterfaces:
            - createVlanOnly: false
              description: blue
              ipPrefix: 1.2.3.1/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '123'
              vrf: blue
            - createVlanOnly: false
              description: green
              ipPrefix: 2.3.5.1/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '235'
              vrf: green
            - createVlanOnly: false
              description: red
              ipPrefix: ''
              stackNumber: '1'
              virtualRouterAddress: 3.1.9.1/24
              vlanId: '319'
              vrf: red
      tags:
        query: Edge-Router-Domain:Internal-FW-Border-Router
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: EXT-FW
              enabled: true
              interfaceName: e6
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:eos6
          vlanInterfaces: []
      tags:
        query: Edge-Router-Domain:External-FW-Border-Router
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: TO-END-DEVICES
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '2'
              tags:
                query: device:eos13
            - inputs:
                stackMember: '1'
              tags:
                query: device:eos11
          vlanInterfaces:
            - createVlanOnly: false
              description: blue-L3
              dhcpHelpers:
                - helperAddress: 3.5.7.9
                - helperAddress: 2.4.8.9
                - helperAddress: 7.5.3.1
              ipPrefix: 2.3.4.11/24
              secIp:
                - secPrefix: 2.3.4.111/24
                - secPrefix: 2.3.4.122/24
                - secPrefix: 2.3.4.113/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '234'
              vrf: blue
            - createVlanOnly: false
              description: green-L3-L2
              ipAddressVirtual: 4.3.2.1/24
              ipPrefix: ''
              virtualRouterAddress: ''
              vlanId: 1/432,2/432
              vrf: green
      tags:
        query: Edge-Router-Domain:Site1
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: EOS8
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '2'
            - description: EOS16
              enabled: true
              interfaceName: e6
              interfaceProfileName: TRUNK
              stackNumber: '2'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:eos9
            - inputs:
                stackMember: '2'
              tags:
                query: device:eos4
          vlanInterfaces:
            - createVlanOnly: false
              description: green
              ipAddressVirtual: 4.3.2.1/24
              ipPrefix: ''
              stackNumber: ''
              virtualRouterAddress: ''
              vlanId: 1/432,2/432
              vrf: green
      tags:
        query: Edge-Router-Domain:Site2
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: floor1-1
              enabled: true
              interfaceName: e2
              interfaceProfileName: TRUNK
              stackNumber: '1'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:eos12
          vlanInterfaces:
            - createVlanOnly: false
              defaultGatewayNextHop: 3.1.9.7
              description: red-floor1-1
              ipPrefix: 3.1.9.12/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor1
            - createVlanOnly: false
              defaultGatewayNextHop: 3.2.0.14
              description: gray-floor1-1
              ipPrefix: 3.2.0.12/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '320'
              vrf: gray-floor1
            - createVlanOnly: false
              defaultGatewayNextHop: 2.3.4.11
              description: blue-floor1-1
              ipPrefix: 2.3.4.12/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '234'
              vrf: blue-floor1
            - createVlanOnly: false
              defaultGatewayNextHop: 4.3.2.1
              description: green-floor1-1
              ipPrefix: 4.3.2.12/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green-floor1
            - createVlanOnly: false
              description: black-floor1
              ipPrefix: 4.3.1.12/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '431'
              vrf: black-floor1
      tags:
        query: End-Devices:Site1
    - inputs:
        devicesGroup:
          interfaceProfiles:
            - aclDirection: in
              aclType: ip
              interfaceProfilesName: TRUNK
              interfaceSpeed: auto
              portChannelGroup: ''
              vlanProfile: Trunk
          interfaceRanges:
            - description: floor2-1
              enabled: true
              interfaceName: e1
              interfaceProfileName: TRUNK
              stackNumber: '1'
            - description: floor2-2
              enabled: true
              interfaceName: e1
              interfaceProfileName: TRUNK
              stackNumber: '2'
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:eos8
            - inputs:
                stackMember: '2'
              tags:
                query: device:eos16
          vlanInterfaces:
            - createVlanOnly: false
              defaultGatewayNextHop: 3.1.9.7
              description: red-floor2-1
              ipPrefix: 3.1.9.8/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor2
            - createVlanOnly: false
              defaultGatewayNextHop: 3.1.9.7
              description: red-floor2-2
              ipPrefix: 3.1.9.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '319'
              vrf: red-floor2
            - createVlanOnly: false
              defaultGatewayNextHop: 3.2.0.14
              description: gray-floor2-1
              ipPrefix: 3.2.0.8/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '320'
              vrf: gray-floor2
            - createVlanOnly: false
              defaultGatewayNextHop: 3.2.0.14
              description: gray-floor2-2
              ipPrefix: 3.2.0.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '320'
              vrf: gray-floor2
            - createVlanOnly: false
              description: black-floor2
              ipPrefix: 4.3.1.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '431'
              vrf: black-floor2
            - createVlanOnly: false
              defaultGatewayNextHop: 4.3.2.1
              description: green-floor2-1
              ipPrefix: 4.3.2.8/24
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green-floor2
            - createVlanOnly: false
              defaultGatewayNextHop: 4.3.2.1
              description: green-floor2-2
              ipPrefix: 4.3.2.16/24
              stackNumber: '2'
              virtualRouterAddress: ''
              vlanId: '432'
              vrf: green-floor2
      tags:
        query: End-Devices:Site2
  dot1XProfiles:
    - dot1XProfileName: d
      dot1x: {}
      portSecurity: {}
  loggingProfiles:
    - logging:
        congestionDrops: none
        linkStatus: enabled
        spanningTree: none
        stormControl: none
      loggingProfileName: L1
  poeProfiles:
    - description: ''
      poe:
        legacyDetect: disabled
        linkDownAction: maintain
        poeNegotiationLldp: disabled
        poeRebootAction: maintain
        poeShutdownAction: maintain
        poeWattsLimit: '3'
        poeWattsLimitClass: '0'
        priority: medium
      poeProfileName: poe1
  qosInstances:
    - classMaps:
        - classMapName: CM0
          match: ''
          matchValue: ''
          type: qos
      classification: []
      devices: []
      instanceName: Q1
      policyMaps:
        - classDefault: '3'
          classMap:
            - classMap: CM0
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '5'
          policyMapName: PM1
          type: qos
      rewriteRules: []
      serviceProfiles:
        - cos: ''
          dscp: ''
          policyMap: PM1
          profileName: Q1
          trust: none
          txQueue: []
      trafficClassToQueue: []
    - classMaps:
        - classMapName: CM3
          match: ip
          matchValue: ''
          type: qos
      classification:
        - classifierValues: 34 36 48
          trafficClass: '0'
          type: dscp
      devices: []
      instanceName: Q2
      policyMaps:
        - classDefault: ''
          classMap:
            - classMap: CM3
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '7'
          policyMapName: PM3
          type: qos
      rewriteRules: []
      serviceProfiles: []
      trafficClassToQueue:
        - dscp: ''
          queue: '1'
          trafficClass: '0'
        - dscp: ''
          queue: '0'
          trafficClass: '1'
  vlanProfiles:
    - allowedVlans: ''
      ipaddress: ''
      lacpEnabled: true
      mlagEnabled: false
      mode: trunk
      name: Trunk
      nativeVlanId: 1
      phoneTrunk: tagged
      phoneVlanId: 0
      portFastEnabled: false
      profileDescription: ''
      speed: auto
