path: []
inputs:
  devices:
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          stack:
            - inputs:
                stackMember: '1'
              tags:
                query: device:6F1A0135F44B1AA9D25473177E89A98A
          vlanInterfaces:
            - createVlanOnly: false
              defaultGatewayNextHop: ''
              description: Server
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: 14.14.14.2/24
              secIp: []
              stackNumber: '1'
              virtualRouterAddress: ''
              vlanId: '14'
              vrf: DC-L3EVPN1
      tags:
        query: device:eos9
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          stack:
            - inputs:
                stackMember: '2'
              tags:
                query: device:95A0ADFCE36FFA14EDE87009E17D4CA2
            - inputs:
                stackMember: '1'
              tags:
                query: device:33D3493C8463E4152C9ED22CF95DB8B2
            - inputs:
                stackMember: '3'
              tags:
                query: device:9C4E0F12E9D8043EA2475ED2FAEF8954
          vlanInterfaces:
            - createVlanOnly: false
              defaultGatewayNextHop: 15.15.15.1
              description: access-eos12
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: 15.15.15.4/24
              secIp: []
              stackNumber: '3'
              virtualRouterAddress: ''
              vlanId: '15'
              vrf: ''
            - createVlanOnly: false
              defaultGatewayNextHop: ''
              description: splines-eos6-eos8
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: ''
              secIp: []
              virtualRouterAddress: 15.15.15.1/24
              vlanId: 1/15,2/15
              vrf: ''
      tags:
        query: Campus:Campus-eos11-eos12-eos13
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          stack:
            - inputs:
                stackMember: '3'
              tags:
                query: device:44204EB637B15866E4BFC29E1AE077D5
            - inputs:
                stackMember: '5'
              tags:
                query: device:6AB72AE457D3B1805E6617A3FB8A6CDE
            - inputs:
                stackMember: '2'
              tags:
                query: device:1AA475846FCB995415949C85C651A277
            - inputs:
                stackMember: '1'
              tags:
                query: device:9C809332310607508C60E4740F3C9359
            - inputs:
                stackMember: '4'
              tags:
                query: device:AA24D1DFC5C00C00061456D452CE6317
          vlanInterfaces:
            - createVlanOnly: false
              defaultGatewayNextHop: ''
              description: splines-eos6-eos8
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: ''
              secIp: []
              virtualRouterAddress: 13.13.13.1/24
              vlanId: 1/13,2/13
              vrf: ''
            - createVlanOnly: false
              defaultGatewayNextHop: 13.13.13.1
              description: eos14-vlan13
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: 13.13.13.4/24
              secIp: []
              stackNumber: '3'
              virtualRouterAddress: ''
              vlanId: '13'
              vrf: ''
            - createVlanOnly: false
              defaultGatewayNextHop: 13.13.13.1
              description: eos15-vlan13
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: 13.13.13.5/29
              secIp: []
              stackNumber: '4'
              virtualRouterAddress: ''
              vlanId: '13'
              vrf: ''
            - createVlanOnly: false
              defaultGatewayNextHop: 13.13.13.1
              description: eos18-vlan13
              dhcpHelpers: []
              ipAddressVirtual: ''
              ipPrefix: 13.13.13.6/24
              secIp: []
              stackNumber: '5'
              virtualRouterAddress: ''
              vlanId: '13'
              vrf: ''
      tags:
        query: Campus:Campus-eos6-eos8-eos14-eos15-eos18
