path: []
inputs:
  devices:
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          vlanInterfaces:
            - description: Server
              ipPrefix: 14.14.14.2/24
              virtualRouterAddress: 14.14.14.1
              vrf: DC-L3EVPN1
              vlanId: '14'
      tags:
        query: device:eos9
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          vlanInterfaces:
            - description: Campus Splines
              virtualRouterAddress: 13.13.13.1/24
              vlanId: 1/13,2/13
            - description: ''
              vlanId: 3/13
              ipPrefix: 13.13.13.4/24
              defaultGatewayNextHop: 13.13.13.1
            - description: ''
              vlanId: 4/13
              ipPrefix: 13.13.13.5/24
              defaultGatewayNextHop: 13.13.13.1
            - description: ''
              vlanId: 5/13
              ipPrefix: 13.13.13.6/24
              defaultGatewayNextHop: 13.13.13.1
      tags:
        query: Campus:Campus-eos6-eos8-eos14-eos15-eos18
    - inputs:
        devicesGroup:
          interfaceProfiles: []
          interfaceRanges: []
          vlanInterfaces:
            - description: Campus Splines
              virtualRouterAddress: 15.15.15.1/24
              vlanId: 1/15,2/15
            - description: ''
              defaultGatewayNextHop: 15.15.15.1
              ipPrefix: 15.15.15.4/24
              vlanId: 3/15
      tags:
        query: Campus:Campus-eos11-eos12-eos13
