path: []
inputs:
  aclNames:
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: permit
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: anyany
      type: ip
    - aclLines:
        - description: ''
          destination: any
          log: false
          permitDenyRemark: deny
          protocol: ip
          seqNumber: '10'
          source: any
          tracked: false
      countersPerEntry: false
      description: ''
      devices: []
      name: any deny
      type: ip
  devices:
    - inputs:
        devicesGroup:
          interface: []
          interfaceRanges:
            - accessVlan: 3
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: e1/1-1/2
              interfaceSpeed: auto
              ipSettings: {}
              name: printers
              portChannelGroup: ''
            - accessVlan: 3
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: vlan3
              interfaceSpeed: auto
              ipSettings:
                virtualRouterAddress: 3.3.3.1/24
              name: printers_ip_address
              portChannelGroup: ''
            - accessVlan: 5
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: e5/1
              interfaceSpeed: auto
              ipSettings: {}
              name: Lobby
              portChannelGroup: ''
            - accessVlan: 5
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: vlan5
              interfaceSpeed: auto
              ipSettings:
                virtualRouterAddress: 5.5.5.1/24
              name: Lobby_ip
              portChannelGroup: ''
            - accessVlan: 6
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: 4/1,5/1
              interfaceSpeed: auto
              ipSettings: {}
              name: sprinklers
              portChannelGroup: ''
      tags:
        query: Campus:Campus-eos6-eos8-eos14-eos15-eos18
    - inputs:
        devicesGroup:
          interface: []
          interfaceRanges:
            - accessVlan: 3
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: e1/2,2/2,3/2
              interfaceSpeed: auto
              ipSettings: {}
              loggingProfile: L1
              name: Cubes_ports
              portChannelGroup: ''
            - accessVlan: 3
              aclDirection: in
              aclType: ip
              description: ''
              enabled: true
              interfaceName: vlan3
              interfaceSpeed: auto
              ipSettings: {}
              name: Cubes_ip
              portChannelGroup: ''
      tags:
        query: Campus:Campus-eos11-eos12-eos13
  dot1XProfiles:
    - dot1XProfileName: d
      dot1x: {}
      portSecurity: {}
  loggingProfiles:
    - logging:
        congestionDrops: none
        linkStatus: enabled
        spanningTree: none
        stormControl: none
      loggingProfileName: L1
  poeProfiles:
    - description: ''
      poe:
        linkDownAction: maintain
        poeNegotiationLldp: disabled
        poeRebootAction: maintain
        poeShutdownAction: maintain
        poeWattsLimit: '3'
        poeWattsLimitClass: '0'
        priority: medium
      poeProfileName: poe1
  qosInstances:
    - classMaps:
        - classMapName: CM0
          match: ''
          matchValue: ''
          type: qos
      classification: []
      devices: []
      instanceName: Q1
      policyMaps:
        - classDefault: '3'
          classMap:
            - classMap: CM0
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '5'
          policyMapName: PM1
          type: qos
      rewriteRules: []
      serviceProfiles:
        - cos: ''
          dscp: ''
          policyMap: PM1
          profileName: Q1
          trust: none
          txQueue: []
      trafficClassToQueue: []
    - classMaps:
        - classMapName: CM3
          match: ip
          matchValue: ''
          type: qos
      classification:
        - classifierValues: 34 36 48
          trafficClass: '0'
          type: dscp
      devices: []
      instanceName: Q2
      policyMaps:
        - classDefault: ''
          classMap:
            - classMap: CM3
              classMapSettings:
                cos: none
                drop: false
                dropPrecedence: none
                dscp: none
                trafficClass: '7'
          policyMapName: PM3
          type: qos
      rewriteRules: []
      serviceProfiles: []
      trafficClassToQueue:
        - dscp: ''
          queue: '1'
          trafficClass: '0'
        - dscp: ''
          queue: '0'
          trafficClass: '1'
  vlanProfiles:
    - allowedVlans: ''
      channelGroup: 3
      ipaddress: ''
      lacpEnabled: true
      mlagEnabled: false
      mode: trunk
      name: port-channel
      nativeVlanId: 1
      phoneTrunk: tagged
      phoneVlanId: 0
      portFastEnabled: true
      profileDescription: ''
      speed: auto
